spring:
  application:
    name: microservice-discovery-eureka
#security:
#  basic:
#   enabled: true          #开启http basic验证
#  user:
#    name: ljf
#    password: ljf12456
---
spring:
  profiles: peer1
server:
  port: 8011
eureka:
  instance:
    hostname: peer1
  client:
    fetch-registry: false
    register-with-eureka: false
    serviceUrl:
      defaultZone: http://peer2:8012/eureka/
---
spring:
  profiles: peer2
server:
  port: 8012
eureka:
  instance:
    hostname: peer2
  client:
    fetch-registry: false
    register-with-eureka: false
    serviceUrl:
      defaultZone: http://peer1:8011/eureka/